name: Copy Files from Another GitHub Repo

on:
  repository_dispatch:
    types: [copy_files]

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Source Repository
      run: |
        git clone https://github.com/bpeng/volc-lab.git
        cd volc-lab
        git fetch --all
        git checkout main  # or the specific branch you want to copy from

    - name: Checkout Target Repository
      uses: actions/checkout@v2
      with:
        repository: bpeng/volc-dash
        token: ${{ secrets.VOLC_PAT }}
        path: volc-dash

    - name: Ensure Destination Directory Exists
      run: mkdir -p volc-dash/dashboards/

    - name: Copy Files
      run: |
        cp -r volc-lab/dashboards/* volc-dash/dashboards/

    - name: Commit and Push Changes to Target Repository
      run: |
        cd volc-dash
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add dashboards
        git commit -m "Copy files from source repository"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.VOLC_PAT }}
