name: copy files from another repo

on:
  repository_dispatch:
    types: [copy_files]

jobs:
  copy-files:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: get branch name
      id: timestamp
      run: echo "branch_name=volc-update-$(date +'%Y%m%d%H%M')" >> $GITHUB_ENV

    - name: Set up Git
      run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

    - name: checkout GNS gitlab repo
      env:
        GITLAB_PAT: ${{ secrets.VOLC_PAT_GL }}
      run: |
          git clone https://oauth2:${GITLAB_PAT}@git.gns.cri.nz:volcanology/volcano-dashboard.git
        # git clone git@git.gns.cri.nz:volcanology/volcano-dashboard.git
          #cd volcano-dashboard
          #git fetch --all
          #git checkout main  # or the specific branch you want to copy from
          #cd ..

    - name: checkout target repository
      uses: actions/checkout@v2
      with:
        repository: bpeng/volc-dash
        token: ${{ secrets.VOLC_PAT }}
        path: volc-dash

    - name: copy files across repos
      run: |
        cd volc-dash
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git checkout -b ${{ env.branch_name }}
        mkdir -p dashboards/
        cp -r ../volcano-dashboard/dashboards/* dashboards/
        git add dashboards
        git commit -m "Copy files from source repository"
        git push --set-upstream origin ${{ env.branch_name }}
      env:
        GITHUB_TOKEN: ${{ secrets.VOLC_PAT }}

    #- name: Create Pull Request
    #  uses: peter-evans/create-pull-request@v4
    #  with:
    #    token: ${{ secrets.VOLC_PAT }}
    #    commit-message: Copy files from source repository
    #    branch: ${{ env.branch_name }}
    #    base: main
    #    path: volc-dash
    #    title: "Copy files from source repository"
    #    body: "This PR copies files from the source repository to the target repository."


